import { useState } from 'react';
import { Link } from 'react-router-dom';
import SEO from '../components/SEO';

const peptideCards = [
  {
    name: 'BPC-157',
    slug: 'bpc-157',
    useCase: 'Tissue Repair & Recovery',
    description: 'One of the most-studied regenerative peptides, widely used in gut healing and musculoskeletal research.',
  },
  {
    name: 'TB-500',
    slug: 'tb-500',
    useCase: 'Systemic Tissue Regeneration',
    description: 'Thymosin Beta-4 fragment studied for broad-spectrum tissue regeneration and angiogenesis.',
  },
  {
    name: 'CJC-1295 DAC',
    slug: 'cjc-1295',
    useCase: 'GH Axis Research',
    description: 'Long-acting GHRH analog with Drug Affinity Complex for once-weekly GH secretion studies.',
  },
  {
    name: 'Ipamorelin',
    slug: 'ipamorelin',
    useCase: 'GH Secretagogue Research',
    description: 'Selective ghrelin mimetic with minimal cortisol/prolactin activity — a benchmark GHRP.',
  },
  {
    name: 'GHK-Cu',
    slug: 'ghk-cu',
    useCase: 'Skin & Anti-Aging Research',
    description: 'Copper peptide tripeptide studied for collagen stimulation, wound healing, and skin remodeling.',
  },
  {
    name: 'Semaglutide',
    slug: 'semaglutide',
    useCase: 'Metabolic & GLP-1 Research',
    description: 'GLP-1 receptor agonist at the center of metabolic disease and weight regulation research.',
  },
];

const comparisonRows = [
  { feature: 'HPLC Purity Testing', us: true, them: true },
  { feature: 'Third-Party COA', us: true, them: false, theirLabel: 'Limited' },
  { feature: 'Certificate Available Online', us: true, them: false, theirLabel: 'No' },
  { feature: 'Shipping Speed', us: false, usLabel: '24–48 hrs', them: false, theirLabel: '3–5 days' },
  { feature: 'Customer Support', us: true, them: false, theirLabel: 'Limited' },
  { feature: 'Business Status', us: false, usLabel: 'Active ✓', them: false, theirLabel: 'Closed ✗', theirRed: true },
];

const faqs = [
  {
    id: 'why-closed',
    question: 'Why did Science.bio close?',
    answer:
      'Science.bio ceased operations in January 2026 due to a combination of regulatory pressures and business challenges facing the research peptide market in 2025–2026. While they were a respected supplier, the evolving compliance landscape made continued operations untenable for their model.',
  },
  {
    id: 'same-quality',
    question: 'Are your peptides the same quality as Science.bio?',
    answer:
      'Yes — and arguably higher. Every batch we ship is HPLC-verified for 98%+ purity with a downloadable Certificate of Analysis. Science.bio offered COAs on a limited basis; we provide one with every single order, no exceptions.',
  },
  {
    id: 'same-peptides',
    question: 'Can I get the same peptides I ordered from Science.bio?',
    answer:
      'In nearly all cases, yes. We carry the full spectrum of major research peptides including BPC-157, TB-500, CJC-1295 DAC, Ipamorelin, GHK-Cu, Semaglutide, PT-141, Melanotan II, and more. Visit our peptides catalog to browse the complete inventory.',
  },
  {
    id: 'shipping',
    question: 'How quickly can I get my order?',
    answer:
      'Orders placed before 2 PM EST ship same-day. Standard processing is 24–48 hours. We offer multiple shipping options including 2-day and overnight at checkout. All orders include tracking.',
  },
  {
    id: 'coa',
    question: 'Do you have Certificates of Analysis?',
    answer:
      'Yes — every batch, without exception. COAs are generated by an independent third-party laboratory and are downloadable directly from our COA Lookup tool at /coa-lookup. You can verify purity, identity, and batch number before your order even arrives.',
  },
];

const ScienceBioAlternativePage = () => {
  const [openFaq, setOpenFaq] = useState<string | null>(null);

  const toggleFaq = (id: string) => {
    setOpenFaq((prev) => (prev === id ? null : id));
  };

  return (
    <>
      <SEO
        title="Science.bio Alternative | Research-Grade Peptides"
        description="Science.bio has closed. PurestPeptides offers the same research-grade peptides with HPLC-verified purity and COA on every order. Shop BPC-157, TB-500, Semaglutide & more."
        canonicalUrl="https://purestpeptides.com/science-bio-alternative"
      />

      {/* ── ANNOUNCEMENT BANNER ── */}
      <div className="bg-teal-600 py-2.5 px-4 text-center">
        <p className="text-white text-sm font-medium">
          <span className="font-bold">Science.bio has closed.</span>{' '}
          PurestPeptides offers the same research-grade quality — with better transparency.
        </p>
      </div>

      {/* ── HERO ── */}
      <section className="pt-24 md:pt-32 pb-16 md:pb-24 bg-gradient-to-br from-navy-950 via-navy-900 to-navy-800 relative overflow-hidden">
        {/* Background grid texture */}
        <div className="absolute inset-0 opacity-5">
          <div
            className="absolute inset-0"
            style={{
              backgroundImage:
                'linear-gradient(rgba(255,255,255,0.15) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.15) 1px, transparent 1px)',
              backgroundSize: '40px 40px',
            }}
          />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="max-w-3xl mx-auto text-center">
            {/* Badge */}
            <span className="inline-flex items-center gap-2 px-4 py-1.5 bg-teal-500/20 border border-teal-500/40 text-teal-300 text-sm font-medium rounded-full mb-6">
              <span className="w-2 h-2 rounded-full bg-teal-400 animate-pulse" />
              Trusted by Researchers Since 2023
            </span>

            <h1 className="font-display text-4xl md:text-5xl lg:text-6xl text-white leading-tight mb-6">
              Looking for a{' '}
              <span className="text-teal-400">Science.bio</span>{' '}
              Alternative?
            </h1>

            <p className="text-slate-300 text-lg md:text-xl leading-relaxed mb-8 max-w-2xl mx-auto">
              Science.bio closed its doors in January 2026, leaving thousands of researchers
              without a trusted peptide source. PurestPeptides delivers the same research-grade
              standards you relied on — with full COA transparency on every order.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Link
                to="/peptides"
                className="inline-flex items-center justify-center gap-2 px-8 py-3.5 bg-teal-500 hover:bg-teal-400 text-white font-semibold rounded-lg transition-colors duration-200"
              >
                Browse Research Peptides
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                </svg>
              </Link>
              <Link
                to="/coa-lookup"
                className="inline-flex items-center justify-center gap-2 px-8 py-3.5 border border-slate-600 hover:border-teal-500 text-slate-200 hover:text-teal-300 font-semibold rounded-lg transition-colors duration-200"
              >
                View Certificates of Analysis
              </Link>
            </div>

            {/* Stats bar */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 max-w-2xl mx-auto">
              {[
                { stat: '98%+', label: 'Verified Purity' },
                { stat: '24 hrs', label: 'Ships Same Day' },
                { stat: 'Every Batch', label: 'COA Included' },
              ].map(({ stat, label }) => (
                <div key={label} className="text-center">
                  <div className="font-display text-3xl font-bold text-teal-400 mb-1">{stat}</div>
                  <div className="text-slate-400 text-sm">{label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── COMPARISON TABLE ── */}
      <section className="py-16 md:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="inline-block px-3 py-1 bg-teal-50 text-teal-700 text-sm font-medium rounded-full mb-4">
              Side-by-Side Comparison
            </span>
            <h2 className="font-display text-3xl md:text-4xl text-navy-900 mb-4">
              PurestPeptides vs. Science.bio
            </h2>
            <p className="text-slate-500 max-w-xl mx-auto">
              See how we stack up against the supplier you trusted — and why researchers are
              making the switch.
            </p>
          </div>

          <div className="max-w-3xl mx-auto overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr>
                  <th className="text-left py-4 px-6 text-slate-500 font-medium text-sm uppercase tracking-wide w-1/2">
                    Feature
                  </th>
                  <th className="py-4 px-6 w-1/4">
                    <div className="flex flex-col items-center gap-1">
                      <span className="text-navy-900 font-semibold text-base">PurestPeptides</span>
                      <span className="text-xs bg-teal-100 text-teal-700 px-2 py-0.5 rounded-full font-medium">
                        Active
                      </span>
                    </div>
                  </th>
                  <th className="py-4 px-6 w-1/4">
                    <div className="flex flex-col items-center gap-1">
                      <span className="text-slate-500 font-semibold text-base">Science.bio</span>
                      <span className="text-xs bg-slate-100 text-slate-500 px-2 py-0.5 rounded-full font-medium">
                        Closed Jan 2026
                      </span>
                    </div>
                  </th>
                </tr>
              </thead>
              <tbody>
                {comparisonRows.map((row, idx) => (
                  <tr
                    key={row.feature}
                    className={idx % 2 === 0 ? 'bg-slate-50' : 'bg-white'}
                  >
                    <td className="py-4 px-6 text-navy-800 font-medium text-sm">{row.feature}</td>
                    <td className="py-4 px-6 border-l-2 border-teal-400">
                      <div className="flex justify-center">
                        {row.usLabel ? (
                          <span className="text-teal-600 font-semibold text-sm">{row.usLabel}</span>
                        ) : row.us ? (
                          <span className="flex items-center justify-center w-7 h-7 bg-teal-100 rounded-full">
                            <svg className="w-4 h-4 text-teal-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                            </svg>
                          </span>
                        ) : (
                          <span className="flex items-center justify-center w-7 h-7 bg-red-100 rounded-full">
                            <svg className="w-4 h-4 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="py-4 px-6">
                      <div className="flex justify-center">
                        {row.theirLabel ? (
                          <span className={`text-sm font-medium ${row.theirRed ? 'text-red-500' : 'text-slate-400'}`}>
                            {row.theirLabel}
                          </span>
                        ) : row.them ? (
                          <span className="flex items-center justify-center w-7 h-7 bg-slate-100 rounded-full">
                            <svg className="w-4 h-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                            </svg>
                          </span>
                        ) : (
                          <span className="flex items-center justify-center w-7 h-7 bg-red-50 rounded-full">
                            <svg className="w-4 h-4 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                          </span>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* ── PEPTIDE REPLACEMENT GRID ── */}
      <section className="py-16 md:py-24 bg-gradient-to-br from-navy-950 via-navy-900 to-navy-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="inline-block px-3 py-1 bg-teal-500/20 text-teal-300 text-sm font-medium rounded-full border border-teal-500/30 mb-4">
              Direct Replacements
            </span>
            <h2 className="font-display text-3xl md:text-4xl text-white mb-4">
              Top Science.bio Products — Now Available Here
            </h2>
            <p className="text-slate-400 max-w-xl mx-auto">
              Every peptide Science.bio carried, stocked and HPLC-verified with a COA
              on every batch.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {peptideCards.map((peptide) => (
              <div
                key={peptide.slug}
                className="bg-navy-800/60 border border-navy-700/50 rounded-xl p-6 hover:border-teal-500/40 hover:bg-navy-800/80 transition-all duration-200 group"
              >
                <div className="flex items-start justify-between mb-3">
                  <h3 className="font-display text-xl text-white font-semibold">{peptide.name}</h3>
                  <span className="flex-shrink-0 text-xs bg-teal-500/20 text-teal-300 border border-teal-500/30 px-2 py-1 rounded-full font-medium">
                    98%+ purity
                  </span>
                </div>
                <p className="text-teal-400 text-sm font-medium mb-3">{peptide.useCase}</p>
                <p className="text-slate-400 text-sm leading-relaxed mb-5">{peptide.description}</p>
                <Link
                  to={`/peptides/${peptide.slug}`}
                  className="inline-flex items-center gap-1.5 text-teal-400 hover:text-teal-300 font-medium text-sm transition-colors group-hover:gap-2.5 duration-200"
                >
                  View Details
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                  </svg>
                </Link>
              </div>
            ))}
          </div>

          <div className="text-center mt-10">
            <Link
              to="/peptides"
              className="inline-flex items-center gap-2 px-8 py-3.5 bg-teal-500 hover:bg-teal-400 text-white font-semibold rounded-lg transition-colors duration-200"
            >
              Browse Full Catalog
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
              </svg>
            </Link>
          </div>
        </div>
      </section>

      {/* ── TRUST SIGNALS ── */}
      <section className="py-16 md:py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="inline-block px-3 py-1 bg-teal-50 text-teal-700 text-sm font-medium rounded-full mb-4">
              Why Researchers Choose Us
            </span>
            <h2 className="font-display text-3xl md:text-4xl text-navy-900 mb-4">
              Research-Grade Standards You Can Verify
            </h2>
            <p className="text-slate-500 max-w-xl mx-auto">
              We don't ask you to take our word for it — every claim is backed by
              documentation you can download.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                icon: (
                  <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                  </svg>
                ),
                title: 'ISO-Standard Testing',
                items: [
                  'HPLC purity verification on every batch',
                  'Mass spectrometry identity confirmation',
                  'Independent third-party laboratory',
                ],
              },
              {
                icon: (
                  <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                ),
                title: 'Full COA Transparency',
                items: [
                  'Certificate of Analysis on every order',
                  'Downloadable via /coa-lookup',
                  'Batch-level traceability',
                ],
              },
              {
                icon: (
                  <svg className="w-7 h-7" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                ),
                title: 'Researcher-First Operations',
                items: [
                  'US-based operations and fulfillment',
                  'No minimum order requirement',
                  'Same-day shipping on orders before 2 PM',
                ],
              },
            ].map(({ icon, title, items }) => (
              <div key={title} className="bg-slate-50 rounded-xl p-8 border border-slate-100">
                <div className="flex items-center justify-center w-14 h-14 bg-teal-50 text-teal-600 rounded-xl mb-5">
                  {icon}
                </div>
                <h3 className="font-display text-xl text-navy-900 font-semibold mb-4">{title}</h3>
                <ul className="space-y-3">
                  {items.map((item) => (
                    <li key={item} className="flex items-start gap-3 text-slate-600 text-sm">
                      <svg className="w-4 h-4 text-teal-500 mt-0.5 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                      </svg>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section className="py-16 md:py-24 bg-slate-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="inline-block px-3 py-1 bg-teal-50 text-teal-700 text-sm font-medium rounded-full mb-4">
              FAQ for Displaced Buyers
            </span>
            <h2 className="font-display text-3xl md:text-4xl text-navy-900 mb-4">
              Questions From Science.bio Customers
            </h2>
            <p className="text-slate-500">
              Everything you need to know about making the transition.
            </p>
          </div>

          <div className="space-y-3">
            {faqs.map(({ id, question, answer }) => (
              <div
                key={id}
                className="bg-white rounded-xl border border-slate-200 overflow-hidden"
              >
                <button
                  onClick={() => toggleFaq(id)}
                  className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left hover:bg-slate-50 transition-colors duration-150"
                  aria-expanded={openFaq === id}
                >
                  <span className="font-medium text-navy-900">{question}</span>
                  <span className="flex-shrink-0">
                    <svg
                      className={`w-5 h-5 text-teal-500 transition-transform duration-200 ${openFaq === id ? 'rotate-45' : ''}`}
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                    </svg>
                  </span>
                </button>
                {openFaq === id && (
                  <div className="px-6 pb-5">
                    <p className="text-slate-600 leading-relaxed text-sm">{answer}</p>
                    {id === 'coa' && (
                      <Link
                        to="/coa-lookup"
                        className="inline-flex items-center gap-1.5 mt-3 text-teal-600 hover:text-teal-700 text-sm font-medium transition-colors"
                      >
                        Search our COA database →
                      </Link>
                    )}
                    {id === 'same-peptides' && (
                      <Link
                        to="/peptides"
                        className="inline-flex items-center gap-1.5 mt-3 text-teal-600 hover:text-teal-700 text-sm font-medium transition-colors"
                      >
                        Browse the full catalog →
                      </Link>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FINAL CTA ── */}
      <section className="py-16 md:py-24 bg-gradient-to-br from-navy-950 via-navy-900 to-navy-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <span className="inline-block px-3 py-1 bg-teal-500/20 text-teal-300 text-sm font-medium rounded-full border border-teal-500/30 mb-6">
            The Trusted Science.bio Replacement
          </span>
          <h2 className="font-display text-3xl md:text-5xl text-white mb-6 max-w-2xl mx-auto leading-tight">
            Start Your Research Order Today
          </h2>
          <p className="text-slate-300 text-lg mb-10 max-w-xl mx-auto leading-relaxed">
            Join thousands of researchers who've transitioned to PurestPeptides — same
            research-grade quality, more transparency, and an active supplier you can rely on.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/peptides"
              className="inline-flex items-center justify-center gap-2 px-10 py-4 bg-teal-500 hover:bg-teal-400 text-white font-semibold rounded-lg transition-colors duration-200 text-lg"
            >
              Shop Peptides
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
              </svg>
            </Link>
            <Link
              to="/coa-lookup"
              className="inline-flex items-center justify-center gap-2 px-10 py-4 border border-slate-600 hover:border-teal-500 text-slate-200 hover:text-teal-300 font-semibold rounded-lg transition-colors duration-200 text-lg"
            >
              View Our COAs
            </Link>
          </div>
        </div>
      </section>
    </>
  );
};

export default ScienceBioAlternativePage;
